minimum_pre_commit_version: '2.9.0'
repos:
- repo: https://github.com/bwhmather/ssort
  rev: master
  hooks:
  - id: ssort
    types_or: [python]
- repo: https://github.com/Zac-HD/shed
  rev: 2023.6.1
  hooks:
    - id: shed
      args: [--refactor, --py311-plus]
      types_or: [python]
